title: Census of Manufacturers Image and Data Archive
description: >-
  Historical census data and images from the Census of Manufacturers
baseurl: ""
url: "http://localhost:4000"

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Collections
collections:
  census_data:
    output: true
  clean_data:
    output: true
    permalink: /clean-data/:path/

# Default front matter
defaults:
  - scope:
      path: ""
      type: "census_data"
    values:
      layout: "census_data"
  - scope:
      path: ""
      type: "clean_data"
    values:
      layout: "clean_data"

# Custom settings
default_state_template: false  # Disable plugin - using generated pages instead
